services:
  flask:
    build: .
    container_name: restaurant_flask
    working_dir: /app
    environment:
      FLASK_APP: app/app.py
      FLASK_DEBUG: "1"          # remove/turn off in production
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  streamlit:
    build: .
    container_name: restaurant_streamlit
    working_dir: /app
    command: streamlit run app/streamlit.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped
